### ISSUE TITLE
完善redsocks2界面提示和单位等说明

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/luci-1#7]
基于
```
stale_time = 900; // Seconds to stale an IP in cache since it is added
                      // into cahce.
                      // Set it to 0 to disable cache stale.
    port_check = 1;   // Whether to distinguish port number in address
    cache_file = "/tmp/ipcache.txt"; // File used to store blocked IP's in cache.
    autosave_interval = 3600; // Interval for saving ip cache into file.
                              // Set it to 0 to disable autosave.
    // When autosave_interval and stale_time are both 0, IP cache behaves like
    // a static blacklist. 
```
https://github.com/wongsyrone/luci-1/blob/master/applications/luci-app-redsocks2/po/zh-cn/redsocks2.po
https://github.com/wongsyrone/luci-1/blob/master/applications/luci-app-redsocks2/luasrc/model/cbi/redsocks2/advanced.lua

**Comment by wongsyrone** [comment]
@semigodking 能帮忙解释一下 stale_time 和 autosave_interval 吗

**Comment by semigodking** [comment]
stale-time:  从IP被加入屏蔽缓存开始，多长时间后相应条目被认为是过期的，无效的。也就是说，相应IP需再次被判定为被屏蔽才会再次加入缓存。

autosave_interval: 非常明确，自动保存缓存内容到文件的周期。

Semigod King
2015年4月30日 下午9:31于 "Syrone Wong" <notifications@github.com>写道：

**Comment by wongsyrone** [comment]
```
stale_time - 整数。从一个IP被加入缓存时或从上次被判定为被屏蔽IP时开始，如果时间达到此设置值，则将此IP从缓存中清除。减小此值有利于快速恢复个别IP因偶然被误判或短时间服务中断而被加入缓存的服务。增加此值有利于加入到被屏蔽IP的访问。
autosave_interval - 整数。自动保存缓存内容到文件的周期，0 表示不自动保存。不应该设置太小，频繁写入文件会影响正常转发的效率与响应速度。
```
datatype and()

**Comment by wongsyrone** [comment]
@semigodking  其中 autosave_interval 的单位是秒吗

**Comment by semigodking** [comment]
是的

Semigod King
2015年5月1日 上午11:36于 "Syrone Wong" <notifications@github.com>写道：
